In [9]:
from scipy import stats
import numpy as np

The instruction did not specify where the number of goals attempted, $n$, comes from. I assume that it comes from a uniform distribution over integers between 0 and 20.

In [23]:
alpha = 1
beta = 1
n_players = 3
n_games = 4

k = np.empty((n_players, n_games))
for i in range(n_players):
    p = stats.beta(alpha,beta).rvs()
    for j in range(n_games):
        n = np.random.randint(21)
        k[i,j] = stats.binom(n, p).rvs()

In [25]:
print(k)

[[1. 1. 1. 2.]
 [1. 7. 2. 1.]
 [5. 0. 0. 2.]]
